services:
  postgres:
    image: postgres:16-alpine
    container_name: qr_platform_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: qr_platform
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: qr_platform_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@qrplatform.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  pgdata:
    driver: local
